[package]
name = "calc"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[workspace]
members = ["ccalc"]

[dependencies]
expect-test = "1"
cc = "1"
crossbeam-utils = "*"
